### ISSUE TITLE
Mob health color bug

### ISSUE THREAD

**Issue by kalavera** [Ko0z/UnitFramesImproved_TBC#1]
Thanks for this backport. It work perfectly apart from mob health bar colors bahaving weird. NPC's having class colors is fine with me but sometimes a hostile mob gets a green health bar. 

Oh yes and the mobs name have the same color if they are aggresive, neutral or friendly.

**Comment by Ko0z** [comment]
@kalavera Should be resolved in v0.5! thanks for reporting.
